# Generated by Django 4.2.6 on 2023-10-18 11:56

from django.db import migrations, models
import utils.modelvalidator


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.modelvalidator.validate_image]),
        ),
    ]
